// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZANvk3cwl-5PabdR6xFE96PR8s5pAVSg',
    appId: '1:669922434505:web:c710de82d3b7a3757f9c18',
    messagingSenderId: '669922434505',
    projectId: 'login-page-b7c0e',
    authDomain: 'login-page-b7c0e.firebaseapp.com',
    storageBucket: 'login-page-b7c0e.appspot.com',
    measurementId: 'G-TEWNRZTEHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwR9R9SBsQ2mjj2WFyAkXbR6HgIEHLph4',
    appId: '1:669922434505:android:54fe1eae8ae757147f9c18',
    messagingSenderId: '669922434505',
    projectId: 'login-page-b7c0e',
    storageBucket: 'login-page-b7c0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhmHyiKfBbuPUnAeRXfgnnr5LgZQnSjts',
    appId: '1:669922434505:ios:5a5a2fa533311f657f9c18',
    messagingSenderId: '669922434505',
    projectId: 'login-page-b7c0e',
    storageBucket: 'login-page-b7c0e.appspot.com',
    iosBundleId: 'com.example.loginTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhmHyiKfBbuPUnAeRXfgnnr5LgZQnSjts',
    appId: '1:669922434505:ios:09fda25a7ab316f37f9c18',
    messagingSenderId: '669922434505',
    projectId: 'login-page-b7c0e',
    storageBucket: 'login-page-b7c0e.appspot.com',
    iosBundleId: 'com.example.loginTask.RunnerTests',
  );
}
